name: MT Arxiv Digest

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes for testing
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm trigger works
        run: echo "Triggered at $(date)"
